version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://manoranjanheremano:gJbpCkWHuV1NeTgQ@cluster0.iprim.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - CHROMA_URL=http://chromadb:8000
      - JWT_SECRET=manoranjanheremano
      - PORT=5000
    volumes:
      - backend_data:/app/controllers/temp
    depends_on:
      - chromadb
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/api
    networks:
      - app-network
    depends_on:
      - backend

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
  chroma_data: