version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: eduub-chromadb
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: eduub_backend:latest
    container_name: eduub-backend
    ports:
      - "5000:5000"
    environment:
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5000,https://localhost:5173,https://localhost:5000,http://127.0.0.1:5173,http://127.0.0.1:5000,https://eduub-ai.vercel.app,https://eduub-ai.onrender.com
      - CHROMA_URL=http://eduub-chromadb:8000
      - NODE_ENV=production
      - CLOUDINARY_CLOUD_NAME=dko27wuzc
      - CLOUDINARY_API_KEY=869282847493747
      - CLOUDINARY_API_SECRET=bzjlOOEJhvzz5TnxPeLFk5nVbaU
      - GROQ_API_KEY=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
    volumes:
      - ./backend/temp:/app/controllers/temp
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: eduub_frontend:latest
    container_name: eduub-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=https://eduub-ai.onrender.com/api
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5000,https://localhost:5173,https://localhost:5000,http://127.0.0.1:5173,http://127.0.0.1:5000,https://eduub-ai.vercel.app,https://eduub-ai.onrender.com
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge