services:
  backend:
    build: ./backend
    image: eduub_backend:latest
    container_name: eduub-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://manoranjanheremano:gJbpCkWHuV1NeTgQ@cluster0.iprim.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - CHROMA_URL=http://eduub-chromadb:8000
      - JWT_SECRET=manoranjanheremano
      - PORT=5000
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5000,https://localhost:5173,https://localhost:5000,http://127.0.0.1:5173,http://127.0.0.1:5000,http://64.227.152.247:5173,https://eduub.mano.systems,http://eduub.mano.systems,http://167.71.229.78:5173
      - CLOUDINARY_CLOUD_NAME=dko27wuzc
      - CLOUDINARY_API_KEY=869282847493747
      - CLOUDINARY_API_SECRET=bzjlOOEJhvzz5TnxPeLFk5nVbaU
      - GROQ_API_KEY=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
    volumes:
      - ./backend/temp:/app/controllers/temp
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: eduub_frontend:latest
    container_name: eduub-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=https://eduubserver.mano.systems/api
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5000,https://localhost:5173,https://localhost:5000,http://127.0.0.1:5173,http://127.0.0.1:5000,http://64.227.152.247:5173,https://eduub.mano.systems,http://eduub.mano.systems,http://167.71.229.78:5173
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: eduub-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge